@host = https://localhost:5001
@token = your-jwt-token-here

### Login with Active Directory credentials
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "your-ad-username",
  "password": "your-password"
}
###

### Check authentication status
GET {{host}}/api/auth/status
###

### Download image (root folder)
GET {{host}}/img/photo.jpg
###

### Download image (subdirectory)
GET {{host}}/img/gallery/vacation.jpg
###

### Download image (nested subdirectories)
GET {{host}}/img/2024/summer/beach.png
###

### Download image (with authentication)
GET {{host}}/img/photo.jpg
Authorization: Bearer {{token}}
###

### Get file metadata (root file)
GET {{host}}/img/photo.jpg/metadata
###

### Get file metadata (subdirectory)
GET {{host}}/img/gallery/vacation.jpg/metadata
###

### Get file metadata (with authentication)
GET {{host}}/img/gallery/vacation.jpg/metadata
Authorization: Bearer {{token}}
###
